PAYG_Payroll/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PAYG_Payroll.Models;

namespace PAYG_Payroll.Controllers
{
    [Authorize]
    public class CompaniesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Companies
        public ActionResult Index()
        {
            return View(db.Companies.ToList());
        }

        // GET: Companies/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "comp_name,comp_add1,comp_add2,comp_add3,comp_add4,comp_towncity,comp_county,comp_postcode,comp_bankname,comp_sortcode,comp_accountnum,comp_payeref,comp_payeaccount,comp_hmrcusername,comp_hmrcpassword,comp_normalpaydayofweek,comp_normlapaydayofMonth,comp_employerallawance")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Companies.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(company);
        }

        // GET: Companies/Edit/5
        public ActionResult Edit()
        {
            int id = 1;
            Company company = db.Companies.Find(id);
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "comp_name,comp_add1,comp_add2,comp_add3,comp_add4,comp_towncity,comp_county,comp_postcode,comp_bankname,comp_sortcode,comp_accountnum,comp_payeref,comp_payeaccount")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Company company = db.Companies.Find(id);
            db.Companies.Remove(company);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PAYG_Payroll/Controllers/EmployeeListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PAYG_Payroll.Models;

namespace PAYG_Payroll.Controllers
{
    public class EmployeeListController : Controller
    {
      

        public PartialViewResult EmpAll()
        {
            List<Employee> model = new List<Employee>().OrderBy(x => x.FirstName).ToList();
            return PartialView("~/Views/Shared/_EmployeeList", model);
        }
        public ActionResult EmpActive()
        {
            return View();
        }
        public ActionResult EmpInactive()
        {
            return View();
        }
        public ActionResult Index()
        {

            return View();
        }
    }
}

PAYG_Payroll/Controllers/PayWeeksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PAYG_Payroll.Models;

namespace PAYG_Payroll.Controllers
{
    [Authorize]
    public class PayWeeksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

    
        
        public ActionResult Index()
        {

            return View(db.PayWeeks.ToList());
        }

        // GET: PayWeeks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PayWeeks payWeeks = db.PayWeeks.Find(id);
            if (payWeeks == null)
            {
                return HttpNotFound();
            }
            return View(payWeeks);
        }

        // GET: PayWeeks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PayWeeks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,StartDate,EndDate,PayDate,Year,WeekNumber,RotaWeek,IsProcessed,Branch")] PayWeeks payWeeks)
        {
            if (ModelState.IsValid)
            {
                db.PayWeeks.Add(payWeeks);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(payWeeks);
        }

        // GET: PayWeeks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PayWeeks payWeeks = db.PayWeeks.Find(id);
            if (payWeeks == null)
            {
                return HttpNotFound();
            }
            return View(payWeeks);
        }

        // POST: PayWeeks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StartDate,EndDate,PayDate,Year,WeekNumber,RotaWeek,IsProcessed,Branch")] PayWeeks payWeeks)
        {
            if (ModelState.IsValid)
            {
                db.Entry(payWeeks).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(payWeeks);
        }

        // GET: PayWeeks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PayWeeks payWeeks = db.PayWeeks.Find(id);
            if (payWeeks == null)
            {
                return HttpNotFound();
            }
            return View(payWeeks);
        }

        // POST: PayWeeks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PayWeeks payWeeks = db.PayWeeks.Find(id);
            db.PayWeeks.Remove(payWeeks);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PAYG_Payroll/Views/Shared/_EmployeeList.cshtml
@model IEnumerable<PAYG_Payroll.Models.Employee>

<script src="~/Scripts/jquery-2.1.3.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
        </tr>
    }

</table>
@Ajax.ActionLink(
("Payslips", "EmpAll", new AjaxOptions()
{
    HttpMethod = "GET",
    UpdateTargetId = "DivStudents",
    InsertionMode = InsertionMode.Replace
})

<div id="DivEmployees">

</div>

PAYG_Payroll/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PAYG Payroll</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
        }({
            instrumentationKey:"73aedf75-f63a-4d04-b6f8-3c1313864cdd"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Company Details", "Edit", "Companies")</li>            
                    <li>@Html.ActionLink("Staff", "Index", "Employees")</li>                              
                    <li>@Html.ActionLink("Properties", "Index", "PayWeeks")</li>                    
                    <li>@Html.ActionLink("Types", "Support", "Home")</li>
                    <li>@Html.ActionLink("Attributes", "Index", "PayWeeks")</li>
                    <li>@Html.ActionLink("Owners", "Support", "Home")</li>
                    <li>@Html.ActionLink("Tenants", "Support", "Home")</li>
                    <li>@Html.ActionLink("Prospects", "Support", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Pay As You Go Software (PAYG)</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>